
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSPLUS = 16;
  public static final int CHAR = 41;
  public static final int ARRAYMEM = 40;
  public static final int UMINUS = 7;
  public static final int ENTERO = 27;
  public static final int SI = 34;
  public static final int LPAREN = 8;
  public static final int SEMI = 2;
  public static final int ENTONCES = 36;
  public static final int MINUS = 4;
  public static final int RPAREN = 9;
  public static final int NOT = 25;
  public static final int AND = 24;
  public static final int FINMIENTRAS = 29;
  public static final int SINO = 37;
  public static final int CARACTER = 32;
  public static final int LESSTHAN = 22;
  public static final int OR = 26;
  public static final int MIENTRAS = 33;
  public static final int LN = 12;
  public static final int PLUS = 3;
  public static final int EXP = 11;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 17;
  public static final int EQUAL = 15;
  public static final int TRUE = 18;
  public static final int error = 1;
  public static final int ISEQUAL = 23;
  public static final int NUMBER = 39;
  public static final int COS = 14;
  public static final int ASIGNATION = 20;
  public static final int VECTOR = 31;
  public static final int REAL = 28;
  public static final int LOG = 10;
  public static final int TIMES = 5;
  public static final int ENTRADA = 35;
  public static final int SIN = 13;
  public static final int MORETHAN = 21;
  public static final int BOOLEANO = 30;
  public static final int FALSE = 19;
  public static final int FINSI = 38;
  public static final int DIVISION = 6;
  public static final int IDENTIFIER = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVISION",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "LOG",
  "EXP",
  "LN",
  "SIN",
  "COS",
  "EQUAL",
  "PLUSPLUS",
  "MINUSMINUS",
  "TRUE",
  "FALSE",
  "ASIGNATION",
  "MORETHAN",
  "LESSTHAN",
  "ISEQUAL",
  "AND",
  "NOT",
  "OR",
  "ENTERO",
  "REAL",
  "FINMIENTRAS",
  "BOOLEANO",
  "VECTOR",
  "CARACTER",
  "MIENTRAS",
  "SI",
  "ENTRADA",
  "ENTONCES",
  "SINO",
  "FINSI",
  "NUMBER",
  "ARRAYMEM",
  "CHAR",
  "IDENTIFIER"
  };
}

