
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int SIN = 13;
  public static final int PLUS = 3;
  public static final int RPAREN = 9;
  public static final int EQUAL = 15;
  public static final int COS = 14;
  public static final int SEMI = 2;
  public static final int DIVISION = 6;
  public static final int LN = 12;
  public static final int MINUSMINUS = 17;
  public static final int LPAREN = 8;
  public static final int ARRAYMEM = 19;
  public static final int LOG = 10;
  public static final int EXP = 11;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int PLUSPLUS = 16;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int UMINUS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVISION",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "LOG",
  "EXP",
  "LN",
  "SIN",
  "COS",
  "EQUAL",
  "PLUSPLUS",
  "MINUSMINUS",
  "NUMBER",
  "ARRAYMEM"
  };
}

