
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 29;
  public static final int CHAR = 33;
  public static final int UMINUS = 7;
  public static final int ENTERO = 35;
  public static final int SI = 23;
  public static final int LPAREN = 8;
  public static final int SEMI = 2;
  public static final int ENTONCES = 25;
  public static final int MINUS = 4;
  public static final int REALNUMBER = 32;
  public static final int RPAREN = 9;
  public static final int NOT = 18;
  public static final int AND = 17;
  public static final int FINMIENTRAS = 20;
  public static final int CARACTER = 38;
  public static final int SINO = 26;
  public static final int LESSTHAN = 15;
  public static final int OR = 19;
  public static final int MIENTRAS = 22;
  public static final int PLUS = 3;
  public static final int EOF = 0;
  public static final int RBRACKET = 30;
  public static final int EQUAL = 10;
  public static final int TRUE = 11;
  public static final int error = 1;
  public static final int ISEQUAL = 16;
  public static final int COMA = 28;
  public static final int NUMBER = 31;
  public static final int ASIGNATION = 13;
  public static final int VECTOR = 21;
  public static final int REAL = 36;
  public static final int TIMES = 5;
  public static final int ENTRADA = 24;
  public static final int MORETHAN = 14;
  public static final int BOOLEANO = 37;
  public static final int FALSE = 12;
  public static final int FINSI = 27;
  public static final int DIVISION = 6;
  public static final int IDENTIFIER = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVISION",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "EQUAL",
  "TRUE",
  "FALSE",
  "ASIGNATION",
  "MORETHAN",
  "LESSTHAN",
  "ISEQUAL",
  "AND",
  "NOT",
  "OR",
  "FINMIENTRAS",
  "VECTOR",
  "MIENTRAS",
  "SI",
  "ENTRADA",
  "ENTONCES",
  "SINO",
  "FINSI",
  "COMA",
  "LBRACKET",
  "RBRACKET",
  "NUMBER",
  "REALNUMBER",
  "CHAR",
  "IDENTIFIER",
  "ENTERO",
  "REAL",
  "BOOLEANO",
  "CARACTER"
  };
}

